### ISSUE TITLE
Issue in Generating the results.html file

### ISSUE THREAD

**Issue by nibatandukar** [VerinFast/verinfast#453]
While scanning not getting the results. There is the issue on the jinja Template for the results with ho Head close.

Example results.html file:

<!DOCTYPE html>
    <html lang="en">
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-+dH/1fQ784/j6cY/" crossorigin="anonymous">
    <head>
    <body>
        
        
        
        
        
        
        
        
    </body>

**Comment by aylusltd** [comment]
Thank you so much for your feedback. I've cut a PR to address this issue. You can track it's progress at #478.

Thanks again!
